name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, wasm32-unknown-unknown]

    steps:
    - uses: actions/checkout@v4
    - name: Install rust target
      run: rustup target add ${{matrix.target}}
    - name: Build
      run: cargo build --verbose --target ${{matrix.target}}
    - name: Run tests
      run: cargo test --verbose
